version: '3.3'

services:
  app_db:
    image: mysql:8.0
    container_name: app_db
    ports: 
        - "3350:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: myDb
        MYSQL_USER: user
        MYSQL_PASSWORD: test
        MYSQL_ROOT_PASSWORD: test 
    volumes:
        - ./dump:/docker-entrypoint-initdb.d
        - ./conf:/etc/mysql/conf.d
    networks:
        - default
  app_backend:
    build: ./backend
    container_name: app_backend
    depends_on:
      - app_db
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
      - /usr/app/dist
    ports:
      - "3331:3000"
    networks:
      - default
  app_frontend:
    build: ./frontend
    container_name: app_frontend
    depends_on:
      - app_db
      - app_backend
    volumes:
      - ./frontend:/usr/app
      - /usr/app/dist
      - /usr/app/node_modules
    ports:
      - "3330:4200"
    networks:
      - default
 

